dialog1 = "A grand castle stands atop a misty hill, its stones whispering tales of old. Tall spires reach for the sky, casting shadows over the green valley. Inside, sunlight paints the halls with color. Gardens bloom outside, and a gentle fountain adds peace, inviting visitors to stay."
dialog2 = "You have selected option 1. Here are the details:"
dialog3 = "You have selected option 2. Here are the details:"
dialog4 = "You have selected option 3. Here are the details:"