start_string = "Start"
exit_string = "Quit"

settings_string = "Settings"
credits_string = "Credits"

general_string = "General"
video_string = "Video"
sound_string = "Sound"
controls_string = "Controls"

#Video Settings
fullscreen_string = "FullScreen"
shadows_string = "Shadows"
outline_string = "Outline"

#language
language_string = "English"

#Contrlols Settings
forward_string = "Forward"
backward_string = "Backward"
left_string = "Left"
right_string = "Right"

#interaction
interact_string = "Interact with:"