start_string = "Iniciar"
exit_string = "Salir"

settings_string = "Ajustes"
credits_string = "Créditos"

general_string = "General"
video_string = "Vídeo"
sound_string = "Sonido"
controls_string = "Controles"

#Video Settings
fullscreen_string = "Pantalla Completa"
shadows_string = "Sombras"
outline_string = "Contorno"

#language
language_string = "Español"

#Contrlols Settings
forward_string = "Adelante"
backward_string = "Atrás"
left_string = "Izquierda"
right_string = "Derecha"

#interaction
interact_string = "Interactuar con:"